### ISSUE TITLE
Forge release

### ISSUE THREAD

**Issue by raphink** [mosen/puppet-cups#45]
Hello,

Would it be possible to update the forge modules please?

Thank you!

**Comment by mosen** [comment]
Hi there,
Yes, there are just two open issues that should probably be fixed before releasing. I'll push something new in 4 days.

**Comment by mcanevet** [comment]
What a precise timing ;-)

**Comment by mcanevet** [comment]
@mosen 5 days later... :-)

**Comment by mosen** [comment]
Ahh you got me.
There's still a bug im trying to sort out which is issue #44.

**Comment by mosen** [comment]
Uploaded forge release 1.4.0

**Comment by mcanevet** [comment]
@mosen thank a lot

**Comment by mcanevet** [comment]
@mosen could you please tag the release on github?
