### ISSUE TITLE
Will there be any further releases to Forge?

### ISSUE THREAD

**Issue by mdwheele** [mosen/puppet-cups#70]
Hello! We've been depending on specific commit references from GitHub. The latest release to Forge was 1.4.1 in April 2015. Will there be any more releases to Forge or, at the very least, tagged releases on GitHub?

**Comment by mosen** [comment]
Hey there. 
I'm happy to tag and release the current commit. I haven't been active on this repo though.

**Comment by mdwheele** [comment]
Haha, no worries. Hope my comment didn't come across as jabby; just wanted to poke in 😄 

Cheers

**Comment by mosen** [comment]
No problem! Should do a new release tomorrow if the forge process hasn't changed in 2 years 😛

**Comment by mdwheele** [comment]
@mosen: Just poking as a reminder. Nothing critical :smile: 

Cheers.

**Comment by mosen** [comment]
just checked with the forge and looks good. should be v1.5.0 if all is well.

**Comment by mdwheele** [comment]
Thank you!
